/** Generated by the default template from graphql-java-generator */
package com.rockwell.cif.connector.server.graphql.model;

import com.graphql_java_generator.GraphQLField;
import com.graphql_java_generator.annotation.GraphQLInputType;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLScalar;
import java.util.List;

/**
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLInputType("CartItemUpdateInput")
public class CartItemUpdateInput  {

	public CartItemUpdateInput(){
		// No action
	}

	@GraphQLScalar(fieldName = "cart_item_id", graphQLTypeName = "Int", javaClass = Integer.class)
	Integer cart_item_id;


	@GraphQLNonScalar(fieldName = "customizable_options", graphQLTypeName = "CustomizableOptionInput", javaClass = CustomizableOptionInput.class)
	List<CustomizableOptionInput> customizable_options;


	@GraphQLScalar(fieldName = "quantity", graphQLTypeName = "Float", javaClass = Double.class)
	Double quantity;



	public void setCart_item_id(Integer cart_item_id) {
		this.cart_item_id = cart_item_id;
	}

	public Integer getCart_item_id() {
		return cart_item_id;
	}

	public void setCustomizable_options(List<CustomizableOptionInput> customizable_options) {
		this.customizable_options = customizable_options;
	}

	public List<CustomizableOptionInput> getCustomizable_options() {
		return customizable_options;
	}

	public void setQuantity(Double quantity) {
		this.quantity = quantity;
	}

	public Double getQuantity() {
		return quantity;
	}

    public String toString() {
        return "CartItemUpdateInput {"
				+ "cart_item_id: " + cart_item_id
				+ ", "
				+ "customizable_options: " + customizable_options
				+ ", "
				+ "quantity: " + quantity
        		+ "}";
    }

    /**
	 * Enum of field names
	 */
	 public static enum Field implements GraphQLField {
		Cart_item_id("cart_item_id"),
		Customizable_options("customizable_options"),
		Quantity("quantity");

		private String fieldName;

		Field(String fieldName) {
			this.fieldName = fieldName;
		}

		public String getFieldName() {
			return fieldName;
		}

		public Class<?> getGraphQLType() {
			return this.getClass().getDeclaringClass();
		}

	}

	public static Builder builder() {
			return new Builder();
		}



	/**
	 * Builder
	 */
	public static class Builder {
		private Integer cart_item_id;
		private List<CustomizableOptionInput> customizable_options;
		private Double quantity;


		public Builder withCart_item_id(Integer cart_item_id) {
			this.cart_item_id = cart_item_id;
			return this;
		}
		public Builder withCustomizable_options(List<CustomizableOptionInput> customizable_options) {
			this.customizable_options = customizable_options;
			return this;
		}
		public Builder withQuantity(Double quantity) {
			this.quantity = quantity;
			return this;
		}

		public CartItemUpdateInput build() {
			CartItemUpdateInput _object = new CartItemUpdateInput();
			_object.setCart_item_id(cart_item_id);
			_object.setCustomizable_options(customizable_options);
			_object.setQuantity(quantity);
			return _object;
		}
	}
}
