/** Generated by the default template from graphql-java-generator */
package com.rockwell.cif.connector.server.graphql.model;

import com.graphql_java_generator.GraphQLField;
import com.graphql_java_generator.annotation.GraphQLInputType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLInputType("CreditCardDetailsInput")
public class CreditCardDetailsInput  {

	public CreditCardDetailsInput(){
		// No action
	}

	@GraphQLScalar(fieldName = "cc_exp_month", graphQLTypeName = "Int", javaClass = Integer.class)
	Integer cc_exp_month;


	@GraphQLScalar(fieldName = "cc_exp_year", graphQLTypeName = "Int", javaClass = Integer.class)
	Integer cc_exp_year;


	@GraphQLScalar(fieldName = "cc_last_4", graphQLTypeName = "Int", javaClass = Integer.class)
	Integer cc_last_4;


	@GraphQLScalar(fieldName = "cc_type", graphQLTypeName = "String", javaClass = String.class)
	String cc_type;



	public void setCc_exp_month(Integer cc_exp_month) {
		this.cc_exp_month = cc_exp_month;
	}

	public Integer getCc_exp_month() {
		return cc_exp_month;
	}

	public void setCc_exp_year(Integer cc_exp_year) {
		this.cc_exp_year = cc_exp_year;
	}

	public Integer getCc_exp_year() {
		return cc_exp_year;
	}

	public void setCc_last_4(Integer cc_last_4) {
		this.cc_last_4 = cc_last_4;
	}

	public Integer getCc_last_4() {
		return cc_last_4;
	}

	public void setCc_type(String cc_type) {
		this.cc_type = cc_type;
	}

	public String getCc_type() {
		return cc_type;
	}

    public String toString() {
        return "CreditCardDetailsInput {"
				+ "cc_exp_month: " + cc_exp_month
				+ ", "
				+ "cc_exp_year: " + cc_exp_year
				+ ", "
				+ "cc_last_4: " + cc_last_4
				+ ", "
				+ "cc_type: " + cc_type
        		+ "}";
    }

    /**
	 * Enum of field names
	 */
	 public static enum Field implements GraphQLField {
		Cc_exp_month("cc_exp_month"),
		Cc_exp_year("cc_exp_year"),
		Cc_last_4("cc_last_4"),
		Cc_type("cc_type");

		private String fieldName;

		Field(String fieldName) {
			this.fieldName = fieldName;
		}

		public String getFieldName() {
			return fieldName;
		}

		public Class<?> getGraphQLType() {
			return this.getClass().getDeclaringClass();
		}

	}

	public static Builder builder() {
			return new Builder();
		}



	/**
	 * Builder
	 */
	public static class Builder {
		private Integer cc_exp_month;
		private Integer cc_exp_year;
		private Integer cc_last_4;
		private String cc_type;


		public Builder withCc_exp_month(Integer cc_exp_month) {
			this.cc_exp_month = cc_exp_month;
			return this;
		}
		public Builder withCc_exp_year(Integer cc_exp_year) {
			this.cc_exp_year = cc_exp_year;
			return this;
		}
		public Builder withCc_last_4(Integer cc_last_4) {
			this.cc_last_4 = cc_last_4;
			return this;
		}
		public Builder withCc_type(String cc_type) {
			this.cc_type = cc_type;
			return this;
		}

		public CreditCardDetailsInput build() {
			CreditCardDetailsInput _object = new CreditCardDetailsInput();
			_object.setCc_exp_month(cc_exp_month);
			_object.setCc_exp_year(cc_exp_year);
			_object.setCc_last_4(cc_last_4);
			_object.setCc_type(cc_type);
			return _object;
		}
	}
}
