/** Generated by the default template from graphql-java-generator */
package com.rockwell.cif.connector.server.graphql.model;

import com.graphql_java_generator.annotation.GraphQLEnumType;

/**
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLEnumType("CurrencyEnum")
public enum CurrencyEnum {
	AFN, ALL, AZN, DZD, AOA, ARS, AMD, AWG, AUD, BSD, BHD, BDT, BBD, BYR, BZD, BMD, BTN, BOB, BAM, BWP, BRL, GBP, BND, BGN, BUK, BIF, KHR, CAD, CVE, CZK, KYD, GQE, CLP, CNY, COP, KMF, CDF, CRC, HRK, CUP, DKK, DJF, DOP, XCD, EGP, SVC, ERN, EEK, ETB, EUR, FKP, FJD, GMD, GEK, GEL, GHS, GIP, GTQ, GNF, GYD, HTG, HNL, HKD, HUF, ISK, INR, IDR, IRR, IQD, ILS, JMD, JPY, JOD, KZT, KES, KWD, KGS, LAK, LVL, LBP, LSL, LRD, LYD, LTL, MOP, MKD, MGA, MWK, MYR, MVR, LSM, MRO, MUR, MXN, MDL, MNT, MAD, MZN, MMK, NAD, NPR, ANG, YTL, NZD, NIC, NGN, KPW, NOK, OMR, PKR, PAB, PGK, PYG, PEN, PHP, PLN, QAR, RHD, RON, RUB, RWF, SHP, STD, SAR, RSD, SCR, SLL, SGD, SKK, SBD, SOS, ZAR, KRW, LKR, SDG, SRD, SZL, SEK, CHF, SYP, TWD, TJS, TZS, THB, TOP, TTD, TND, TMM, USD, UGX, UAH, AED, UYU, UZS, VUV, VEB, VEF, VND, CHE, CHW, XOF, WST, YER, ZMK, ZWD, TRY, AZM, ROL, TRL, XPF;
}
