/** Generated by the default template from graphql-java-generator */
package com.rockwell.cif.connector.server.graphql.model;

import com.graphql_java_generator.GraphQLField;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLObjectType("CustomerDownloadableProduct")
public class CustomerDownloadableProduct  {

	public CustomerDownloadableProduct(){
		// No action
	}

	@GraphQLScalar(fieldName = "date", graphQLTypeName = "String", javaClass = String.class)
	String date;


	@GraphQLScalar(fieldName = "download_url", graphQLTypeName = "String", javaClass = String.class)
	String download_url;


	@GraphQLScalar(fieldName = "order_increment_id", graphQLTypeName = "String", javaClass = String.class)
	String order_increment_id;


	@GraphQLScalar(fieldName = "remaining_downloads", graphQLTypeName = "String", javaClass = String.class)
	String remaining_downloads;


	@GraphQLScalar(fieldName = "status", graphQLTypeName = "String", javaClass = String.class)
	String status;



	public void setDate(String date) {
		this.date = date;
	}

	public String getDate() {
		return date;
	}

	public void setDownload_url(String download_url) {
		this.download_url = download_url;
	}

	public String getDownload_url() {
		return download_url;
	}

	public void setOrder_increment_id(String order_increment_id) {
		this.order_increment_id = order_increment_id;
	}

	public String getOrder_increment_id() {
		return order_increment_id;
	}

	public void setRemaining_downloads(String remaining_downloads) {
		this.remaining_downloads = remaining_downloads;
	}

	public String getRemaining_downloads() {
		return remaining_downloads;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getStatus() {
		return status;
	}

    public String toString() {
        return "CustomerDownloadableProduct {"
				+ "date: " + date
				+ ", "
				+ "download_url: " + download_url
				+ ", "
				+ "order_increment_id: " + order_increment_id
				+ ", "
				+ "remaining_downloads: " + remaining_downloads
				+ ", "
				+ "status: " + status
        		+ "}";
    }

    /**
	 * Enum of field names
	 */
	 public static enum Field implements GraphQLField {
		Date("date"),
		Download_url("download_url"),
		Order_increment_id("order_increment_id"),
		Remaining_downloads("remaining_downloads"),
		Status("status");

		private String fieldName;

		Field(String fieldName) {
			this.fieldName = fieldName;
		}

		public String getFieldName() {
			return fieldName;
		}

		public Class<?> getGraphQLType() {
			return this.getClass().getDeclaringClass();
		}

	}

	public static Builder builder() {
			return new Builder();
		}



	/**
	 * Builder
	 */
	public static class Builder {
		private String date;
		private String download_url;
		private String order_increment_id;
		private String remaining_downloads;
		private String status;


		public Builder withDate(String date) {
			this.date = date;
			return this;
		}
		public Builder withDownload_url(String download_url) {
			this.download_url = download_url;
			return this;
		}
		public Builder withOrder_increment_id(String order_increment_id) {
			this.order_increment_id = order_increment_id;
			return this;
		}
		public Builder withRemaining_downloads(String remaining_downloads) {
			this.remaining_downloads = remaining_downloads;
			return this;
		}
		public Builder withStatus(String status) {
			this.status = status;
			return this;
		}

		public CustomerDownloadableProduct build() {
			CustomerDownloadableProduct _object = new CustomerDownloadableProduct();
			_object.setDate(date);
			_object.setDownload_url(download_url);
			_object.setOrder_increment_id(order_increment_id);
			_object.setRemaining_downloads(remaining_downloads);
			_object.setStatus(status);
			return _object;
		}
	}
}
