/** Generated by the default template from graphql-java-generator */
package com.rockwell.cif.connector.server.graphql.model;

import com.graphql_java_generator.GraphQLField;
import com.graphql_java_generator.annotation.GraphQLInputParameters;
import com.graphql_java_generator.annotation.GraphQLInterfaceType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLInterfaceType("CustomizableOptionInterface")
public interface CustomizableOptionInterface  {

	@GraphQLScalar(fieldName = "option_id", graphQLTypeName = "Int", javaClass = Integer.class)
	public void setOption_id(Integer option_id);

	@GraphQLScalar(fieldName = "option_id", graphQLTypeName = "Int", javaClass = Integer.class)
	public Integer getOption_id();

	@GraphQLScalar(fieldName = "required", graphQLTypeName = "Boolean", javaClass = Boolean.class)
	public void setRequired(Boolean required);

	@GraphQLScalar(fieldName = "required", graphQLTypeName = "Boolean", javaClass = Boolean.class)
	public Boolean getRequired();

	@GraphQLScalar(fieldName = "sort_order", graphQLTypeName = "Int", javaClass = Integer.class)
	public void setSort_order(Integer sort_order);

	@GraphQLScalar(fieldName = "sort_order", graphQLTypeName = "Int", javaClass = Integer.class)
	public Integer getSort_order();

	@GraphQLScalar(fieldName = "title", graphQLTypeName = "String", javaClass = String.class)
	public void setTitle(String title);

	@GraphQLScalar(fieldName = "title", graphQLTypeName = "String", javaClass = String.class)
	public String getTitle();
}
