/** Generated by the default template from graphql-java-generator */
package com.rockwell.cif.connector.server.graphql.model;

import com.graphql_java_generator.GraphQLField;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLObjectType("PayflowLinkToken")
public class PayflowLinkToken  {

	public PayflowLinkToken(){
		// No action
	}

	@GraphQLScalar(fieldName = "mode", graphQLTypeName = "PayflowLinkMode", javaClass = PayflowLinkMode.class)
	PayflowLinkMode mode;


	@GraphQLScalar(fieldName = "paypal_url", graphQLTypeName = "String", javaClass = String.class)
	String paypal_url;


	@GraphQLScalar(fieldName = "secure_token", graphQLTypeName = "String", javaClass = String.class)
	String secure_token;


	@GraphQLScalar(fieldName = "secure_token_id", graphQLTypeName = "String", javaClass = String.class)
	String secure_token_id;



	public void setMode(PayflowLinkMode mode) {
		this.mode = mode;
	}

	public PayflowLinkMode getMode() {
		return mode;
	}

	public void setPaypal_url(String paypal_url) {
		this.paypal_url = paypal_url;
	}

	public String getPaypal_url() {
		return paypal_url;
	}

	public void setSecure_token(String secure_token) {
		this.secure_token = secure_token;
	}

	public String getSecure_token() {
		return secure_token;
	}

	public void setSecure_token_id(String secure_token_id) {
		this.secure_token_id = secure_token_id;
	}

	public String getSecure_token_id() {
		return secure_token_id;
	}

    public String toString() {
        return "PayflowLinkToken {"
				+ "mode: " + mode
				+ ", "
				+ "paypal_url: " + paypal_url
				+ ", "
				+ "secure_token: " + secure_token
				+ ", "
				+ "secure_token_id: " + secure_token_id
        		+ "}";
    }

    /**
	 * Enum of field names
	 */
	 public static enum Field implements GraphQLField {
		Mode("mode"),
		Paypal_url("paypal_url"),
		Secure_token("secure_token"),
		Secure_token_id("secure_token_id");

		private String fieldName;

		Field(String fieldName) {
			this.fieldName = fieldName;
		}

		public String getFieldName() {
			return fieldName;
		}

		public Class<?> getGraphQLType() {
			return this.getClass().getDeclaringClass();
		}

	}

	public static Builder builder() {
			return new Builder();
		}



	/**
	 * Builder
	 */
	public static class Builder {
		private PayflowLinkMode mode;
		private String paypal_url;
		private String secure_token;
		private String secure_token_id;


		public Builder withMode(PayflowLinkMode mode) {
			this.mode = mode;
			return this;
		}
		public Builder withPaypal_url(String paypal_url) {
			this.paypal_url = paypal_url;
			return this;
		}
		public Builder withSecure_token(String secure_token) {
			this.secure_token = secure_token;
			return this;
		}
		public Builder withSecure_token_id(String secure_token_id) {
			this.secure_token_id = secure_token_id;
			return this;
		}

		public PayflowLinkToken build() {
			PayflowLinkToken _object = new PayflowLinkToken();
			_object.setMode(mode);
			_object.setPaypal_url(paypal_url);
			_object.setSecure_token(secure_token);
			_object.setSecure_token_id(secure_token_id);
			return _object;
		}
	}
}
