/** Generated by the default template from graphql-java-generator */
package com.rockwell.cif.connector.server.graphql.model;

import com.graphql_java_generator.GraphQLField;
import com.graphql_java_generator.annotation.GraphQLInputParameters;
import com.graphql_java_generator.annotation.GraphQLInterfaceType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLInterfaceType("PhysicalProductInterface")
public interface PhysicalProductInterface  {

	@GraphQLScalar(fieldName = "weight", graphQLTypeName = "Float", javaClass = Double.class)
	public void setWeight(Double weight);

	@GraphQLScalar(fieldName = "weight", graphQLTypeName = "Float", javaClass = Double.class)
	public Double getWeight();
}
