/** Generated by the default template from graphql-java-generator */
package com.rockwell.cif.connector.server.graphql.model;

import com.graphql_java_generator.GraphQLField;
import com.graphql_java_generator.annotation.GraphQLInputType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLInputType("ProductAttributeSortInput")
public class ProductAttributeSortInput  {

	public ProductAttributeSortInput(){
		// No action
	}

	@GraphQLScalar(fieldName = "name", graphQLTypeName = "SortEnum", javaClass = SortEnum.class)
	SortEnum name;


	@GraphQLScalar(fieldName = "position", graphQLTypeName = "SortEnum", javaClass = SortEnum.class)
	SortEnum position;


	@GraphQLScalar(fieldName = "price", graphQLTypeName = "SortEnum", javaClass = SortEnum.class)
	SortEnum price;


	@GraphQLScalar(fieldName = "relevance", graphQLTypeName = "SortEnum", javaClass = SortEnum.class)
	SortEnum relevance;


	public void setName(SortEnum name) {
		this.name = name;
	}

	public SortEnum getName() {
		return name;
	}

	public void setPosition(SortEnum position) {
		this.position = position;
	}

	public SortEnum getPosition() {
		return position;
	}

	public void setPrice(SortEnum price) {
		this.price = price;
	}

	public SortEnum getPrice() {
		return price;
	}

	public void setRelevance(SortEnum relevance) {
		this.relevance = relevance;
	}

	public SortEnum getRelevance() {
		return relevance;
	}

    public String toString() {
        return "ProductAttributeSortInput {"
				+ "name: " + name
				+ ", "
				+ "position: " + position
				+ ", "
				+ "price: " + price
				+ ", "
				+ "relevance: " + relevance
        		+ "}";
    }

    /**
	 * Enum of field names
	 */
	 public static enum Field implements GraphQLField {
		Name("name"),
		Position("position"),
		Price("price"),
		Relevance("relevance");

		private String fieldName;

		Field(String fieldName) {
			this.fieldName = fieldName;
		}

		public String getFieldName() {
			return fieldName;
		}

		public Class<?> getGraphQLType() {
			return this.getClass().getDeclaringClass();
		}

	}

	public static Builder builder() {
			return new Builder();
		}



	/**
	 * Builder
	 */
	public static class Builder {
		private SortEnum name;
		private SortEnum position;
		private SortEnum price;
		private SortEnum relevance;


		public Builder withName(SortEnum name) {
			this.name = name;
			return this;
		}
		public Builder withPosition(SortEnum position) {
			this.position = position;
			return this;
		}
		public Builder withPrice(SortEnum price) {
			this.price = price;
			return this;
		}
		public Builder withRelevance(SortEnum relevance) {
			this.relevance = relevance;
			return this;
		}

		public ProductAttributeSortInput build() {
			ProductAttributeSortInput _object = new ProductAttributeSortInput();
			_object.setName(name);
			_object.setPosition(position);
			_object.setPrice(price);
			_object.setRelevance(relevance);
			return _object;
		}
	}
}
