/** Generated by the default template from graphql-java-generator */
package com.rockwell.cif.connector.server.graphql.model;

import com.graphql_java_generator.GraphQLField;
import com.graphql_java_generator.annotation.GraphQLInputParameters;
import com.graphql_java_generator.annotation.GraphQLInterfaceType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLInterfaceType("ProductLinksInterface")
public interface ProductLinksInterface  {

	@GraphQLScalar(fieldName = "link_type", graphQLTypeName = "String", javaClass = String.class)
	public void setLink_type(String link_type);

	@GraphQLScalar(fieldName = "link_type", graphQLTypeName = "String", javaClass = String.class)
	public String getLink_type();

	@GraphQLScalar(fieldName = "linked_product_sku", graphQLTypeName = "String", javaClass = String.class)
	public void setLinked_product_sku(String linked_product_sku);

	@GraphQLScalar(fieldName = "linked_product_sku", graphQLTypeName = "String", javaClass = String.class)
	public String getLinked_product_sku();

	@GraphQLScalar(fieldName = "linked_product_type", graphQLTypeName = "String", javaClass = String.class)
	public void setLinked_product_type(String linked_product_type);

	@GraphQLScalar(fieldName = "linked_product_type", graphQLTypeName = "String", javaClass = String.class)
	public String getLinked_product_type();

	@GraphQLScalar(fieldName = "position", graphQLTypeName = "Int", javaClass = Integer.class)
	public void setPosition(Integer position);

	@GraphQLScalar(fieldName = "position", graphQLTypeName = "Int", javaClass = Integer.class)
	public Integer getPosition();

	@GraphQLScalar(fieldName = "sku", graphQLTypeName = "String", javaClass = String.class)
	public void setSku(String sku);

	@GraphQLScalar(fieldName = "sku", graphQLTypeName = "String", javaClass = String.class)
	public String getSku();
}
