/** Generated by the default template from graphql-java-generator */
package com.rockwell.cif.connector.server.graphql.model;

import com.graphql_java_generator.annotation.GraphQLInterfaceType;
import com.graphql_java_generator.annotation.GraphQLNonScalar;

/**
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLInterfaceType("SwatchLayerFilterItemInterface")
public interface SwatchLayerFilterItemInterface  {

	@GraphQLNonScalar(fieldName = "swatch_data", graphQLTypeName = "SwatchData", javaClass = SwatchData.class)
	public void setSwatch_data(SwatchData swatch_data);

	@GraphQLNonScalar(fieldName = "swatch_data", graphQLTypeName = "SwatchData", javaClass = SwatchData.class)
	public SwatchData getSwatch_data();
}
