/*
 * Commerce Webservices v2
 * These services manage all of the common commerce functionality, and also include customizations from installed AddOns.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rockwell.cif.connector.hybris.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * B2BCostCenterList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-23T22:16:40.723Z")



public class B2BCostCenterList {
  @SerializedName("costCenters")
  private List<B2BCostCenter> costCenters = null;

  public B2BCostCenterList costCenters(List<B2BCostCenter> costCenters) {
    this.costCenters = costCenters;
    return this;
  }

  public B2BCostCenterList addCostCentersItem(B2BCostCenter costCentersItem) {
    if (this.costCenters == null) {
      this.costCenters = new ArrayList<B2BCostCenter>();
    }
    this.costCenters.add(costCentersItem);
    return this;
  }

   /**
   * Get costCenters
   * @return costCenters
  **/
  @ApiModelProperty(value = "")
  public List<B2BCostCenter> getCostCenters() {
    return costCenters;
  }

  public void setCostCenters(List<B2BCostCenter> costCenters) {
    this.costCenters = costCenters;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    B2BCostCenterList b2BCostCenterList = (B2BCostCenterList) o;
    return Objects.equals(this.costCenters, b2BCostCenterList.costCenters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(costCenters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class B2BCostCenterList {\n");
    
    sb.append("    costCenters: ").append(toIndentedString(costCenters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

