/*
 * Commerce Webservices v2
 * These services manage all of the common commerce functionality, and also include customizations from installed AddOns.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rockwell.cif.connector.hybris.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Representation of a Base Site
 */
@ApiModel(description = "Representation of a Base Site")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-23T22:16:40.723Z")



public class BaseSite {
  @SerializedName("channel")
  private String channel = null;

  @SerializedName("defaultLanguage")
  private Language defaultLanguage = null;

  @SerializedName("defaultPreviewCatalogId")
  private String defaultPreviewCatalogId = null;

  @SerializedName("defaultPreviewCategoryCode")
  private String defaultPreviewCategoryCode = null;

  @SerializedName("defaultPreviewProductCode")
  private String defaultPreviewProductCode = null;

  @SerializedName("locale")
  private String locale = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("stores")
  private List<BaseStore> stores = null;

  @SerializedName("theme")
  private String theme = null;

  @SerializedName("uid")
  private String uid = null;

  @SerializedName("urlEncodingAttributes")
  private List<String> urlEncodingAttributes = null;

  @SerializedName("urlPatterns")
  private List<String> urlPatterns = null;

  public BaseSite channel(String channel) {
    this.channel = channel;
    return this;
  }

   /**
   * Channel
   * @return channel
  **/
  @ApiModelProperty(value = "Channel")
  public String getChannel() {
    return channel;
  }

  public void setChannel(String channel) {
    this.channel = channel;
  }

  public BaseSite defaultLanguage(Language defaultLanguage) {
    this.defaultLanguage = defaultLanguage;
    return this;
  }

   /**
   * Default language for Basesite
   * @return defaultLanguage
  **/
  @ApiModelProperty(value = "Default language for Basesite")
  public Language getDefaultLanguage() {
    return defaultLanguage;
  }

  public void setDefaultLanguage(Language defaultLanguage) {
    this.defaultLanguage = defaultLanguage;
  }

  public BaseSite defaultPreviewCatalogId(String defaultPreviewCatalogId) {
    this.defaultPreviewCatalogId = defaultPreviewCatalogId;
    return this;
  }

   /**
   * Default preview catalog id
   * @return defaultPreviewCatalogId
  **/
  @ApiModelProperty(value = "Default preview catalog id")
  public String getDefaultPreviewCatalogId() {
    return defaultPreviewCatalogId;
  }

  public void setDefaultPreviewCatalogId(String defaultPreviewCatalogId) {
    this.defaultPreviewCatalogId = defaultPreviewCatalogId;
  }

  public BaseSite defaultPreviewCategoryCode(String defaultPreviewCategoryCode) {
    this.defaultPreviewCategoryCode = defaultPreviewCategoryCode;
    return this;
  }

   /**
   * Default preview category code
   * @return defaultPreviewCategoryCode
  **/
  @ApiModelProperty(value = "Default preview category code")
  public String getDefaultPreviewCategoryCode() {
    return defaultPreviewCategoryCode;
  }

  public void setDefaultPreviewCategoryCode(String defaultPreviewCategoryCode) {
    this.defaultPreviewCategoryCode = defaultPreviewCategoryCode;
  }

  public BaseSite defaultPreviewProductCode(String defaultPreviewProductCode) {
    this.defaultPreviewProductCode = defaultPreviewProductCode;
    return this;
  }

   /**
   * Default preview product code
   * @return defaultPreviewProductCode
  **/
  @ApiModelProperty(value = "Default preview product code")
  public String getDefaultPreviewProductCode() {
    return defaultPreviewProductCode;
  }

  public void setDefaultPreviewProductCode(String defaultPreviewProductCode) {
    this.defaultPreviewProductCode = defaultPreviewProductCode;
  }

  public BaseSite locale(String locale) {
    this.locale = locale;
    return this;
  }

   /**
   * Locale data for Basesite
   * @return locale
  **/
  @ApiModelProperty(value = "Locale data for Basesite")
  public String getLocale() {
    return locale;
  }

  public void setLocale(String locale) {
    this.locale = locale;
  }

  public BaseSite name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of Basesite
   * @return name
  **/
  @ApiModelProperty(value = "Name of Basesite")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public BaseSite stores(List<BaseStore> stores) {
    this.stores = stores;
    return this;
  }

  public BaseSite addStoresItem(BaseStore storesItem) {
    if (this.stores == null) {
      this.stores = new ArrayList<BaseStore>();
    }
    this.stores.add(storesItem);
    return this;
  }

   /**
   * List of Basestores
   * @return stores
  **/
  @ApiModelProperty(value = "List of Basestores")
  public List<BaseStore> getStores() {
    return stores;
  }

  public void setStores(List<BaseStore> stores) {
    this.stores = stores;
  }

  public BaseSite theme(String theme) {
    this.theme = theme;
    return this;
  }

   /**
   * Theme of Basesite
   * @return theme
  **/
  @ApiModelProperty(value = "Theme of Basesite")
  public String getTheme() {
    return theme;
  }

  public void setTheme(String theme) {
    this.theme = theme;
  }

  public BaseSite uid(String uid) {
    this.uid = uid;
    return this;
  }

   /**
   * Unique identifier of Basesite
   * @return uid
  **/
  @ApiModelProperty(value = "Unique identifier of Basesite")
  public String getUid() {
    return uid;
  }

  public void setUid(String uid) {
    this.uid = uid;
  }

  public BaseSite urlEncodingAttributes(List<String> urlEncodingAttributes) {
    this.urlEncodingAttributes = urlEncodingAttributes;
    return this;
  }

  public BaseSite addUrlEncodingAttributesItem(String urlEncodingAttributesItem) {
    if (this.urlEncodingAttributes == null) {
      this.urlEncodingAttributes = new ArrayList<String>();
    }
    this.urlEncodingAttributes.add(urlEncodingAttributesItem);
    return this;
  }

   /**
   * List of url encoding attributes
   * @return urlEncodingAttributes
  **/
  @ApiModelProperty(value = "List of url encoding attributes")
  public List<String> getUrlEncodingAttributes() {
    return urlEncodingAttributes;
  }

  public void setUrlEncodingAttributes(List<String> urlEncodingAttributes) {
    this.urlEncodingAttributes = urlEncodingAttributes;
  }

  public BaseSite urlPatterns(List<String> urlPatterns) {
    this.urlPatterns = urlPatterns;
    return this;
  }

  public BaseSite addUrlPatternsItem(String urlPatternsItem) {
    if (this.urlPatterns == null) {
      this.urlPatterns = new ArrayList<String>();
    }
    this.urlPatterns.add(urlPatternsItem);
    return this;
  }

   /**
   * List of url patterns
   * @return urlPatterns
  **/
  @ApiModelProperty(value = "List of url patterns")
  public List<String> getUrlPatterns() {
    return urlPatterns;
  }

  public void setUrlPatterns(List<String> urlPatterns) {
    this.urlPatterns = urlPatterns;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BaseSite baseSite = (BaseSite) o;
    return Objects.equals(this.channel, baseSite.channel) &&
        Objects.equals(this.defaultLanguage, baseSite.defaultLanguage) &&
        Objects.equals(this.defaultPreviewCatalogId, baseSite.defaultPreviewCatalogId) &&
        Objects.equals(this.defaultPreviewCategoryCode, baseSite.defaultPreviewCategoryCode) &&
        Objects.equals(this.defaultPreviewProductCode, baseSite.defaultPreviewProductCode) &&
        Objects.equals(this.locale, baseSite.locale) &&
        Objects.equals(this.name, baseSite.name) &&
        Objects.equals(this.stores, baseSite.stores) &&
        Objects.equals(this.theme, baseSite.theme) &&
        Objects.equals(this.uid, baseSite.uid) &&
        Objects.equals(this.urlEncodingAttributes, baseSite.urlEncodingAttributes) &&
        Objects.equals(this.urlPatterns, baseSite.urlPatterns);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channel, defaultLanguage, defaultPreviewCatalogId, defaultPreviewCategoryCode, defaultPreviewProductCode, locale, name, stores, theme, uid, urlEncodingAttributes, urlPatterns);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BaseSite {\n");
    
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    defaultLanguage: ").append(toIndentedString(defaultLanguage)).append("\n");
    sb.append("    defaultPreviewCatalogId: ").append(toIndentedString(defaultPreviewCatalogId)).append("\n");
    sb.append("    defaultPreviewCategoryCode: ").append(toIndentedString(defaultPreviewCategoryCode)).append("\n");
    sb.append("    defaultPreviewProductCode: ").append(toIndentedString(defaultPreviewProductCode)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    stores: ").append(toIndentedString(stores)).append("\n");
    sb.append("    theme: ").append(toIndentedString(theme)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    urlEncodingAttributes: ").append(toIndentedString(urlEncodingAttributes)).append("\n");
    sb.append("    urlPatterns: ").append(toIndentedString(urlPatterns)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

