/*
 * Commerce Webservices v2
 * These services manage all of the common commerce functionality, and also include customizations from installed AddOns.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rockwell.cif.connector.hybris.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Representation of a Category
 */
@ApiModel(description = "Representation of a Category")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-23T22:16:40.723Z")



public class Category {
  @SerializedName("code")
  private String code = null;

  @SerializedName("image")
  private Image image = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("url")
  private String url = null;

  public Category code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Code of the category
   * @return code
  **/
  @ApiModelProperty(value = "Code of the category")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public Category image(Image image) {
    this.image = image;
    return this;
  }

   /**
   * Category image
   * @return image
  **/
  @ApiModelProperty(value = "Category image")
  public Image getImage() {
    return image;
  }

  public void setImage(Image image) {
    this.image = image;
  }

  public Category name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the category
   * @return name
  **/
  @ApiModelProperty(value = "Name of the category")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Category url(String url) {
    this.url = url;
    return this;
  }

   /**
   * URL of the category
   * @return url
  **/
  @ApiModelProperty(value = "URL of the category")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Category category = (Category) o;
    return Objects.equals(this.code, category.code) &&
        Objects.equals(this.image, category.image) &&
        Objects.equals(this.name, category.name) &&
        Objects.equals(this.url, category.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, image, name, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Category {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

