/*
 * Commerce Webservices v2
 * These services manage all of the common commerce functionality, and also include customizations from installed AddOns.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rockwell.cif.connector.hybris.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Representation of a Delivery Order Entry Group
 */
@ApiModel(description = "Representation of a Delivery Order Entry Group")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-23T22:16:40.723Z")



public class DeliveryOrderEntryGroup {
  @SerializedName("deliveryAddress")
  private Address deliveryAddress = null;

  @SerializedName("entries")
  private List<OrderEntry> entries = null;

  @SerializedName("quantity")
  private Long quantity = null;

  @SerializedName("totalPriceWithTax")
  private Price totalPriceWithTax = null;

  public DeliveryOrderEntryGroup deliveryAddress(Address deliveryAddress) {
    this.deliveryAddress = deliveryAddress;
    return this;
  }

   /**
   * Delivery address for order entry group
   * @return deliveryAddress
  **/
  @ApiModelProperty(value = "Delivery address for order entry group")
  public Address getDeliveryAddress() {
    return deliveryAddress;
  }

  public void setDeliveryAddress(Address deliveryAddress) {
    this.deliveryAddress = deliveryAddress;
  }

  public DeliveryOrderEntryGroup entries(List<OrderEntry> entries) {
    this.entries = entries;
    return this;
  }

  public DeliveryOrderEntryGroup addEntriesItem(OrderEntry entriesItem) {
    if (this.entries == null) {
      this.entries = new ArrayList<OrderEntry>();
    }
    this.entries.add(entriesItem);
    return this;
  }

   /**
   * List of order entries
   * @return entries
  **/
  @ApiModelProperty(value = "List of order entries")
  public List<OrderEntry> getEntries() {
    return entries;
  }

  public void setEntries(List<OrderEntry> entries) {
    this.entries = entries;
  }

  public DeliveryOrderEntryGroup quantity(Long quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Quantity of order entries in a group
   * @return quantity
  **/
  @ApiModelProperty(value = "Quantity of order entries in a group")
  public Long getQuantity() {
    return quantity;
  }

  public void setQuantity(Long quantity) {
    this.quantity = quantity;
  }

  public DeliveryOrderEntryGroup totalPriceWithTax(Price totalPriceWithTax) {
    this.totalPriceWithTax = totalPriceWithTax;
    return this;
  }

   /**
   * Total price with tax
   * @return totalPriceWithTax
  **/
  @ApiModelProperty(value = "Total price with tax")
  public Price getTotalPriceWithTax() {
    return totalPriceWithTax;
  }

  public void setTotalPriceWithTax(Price totalPriceWithTax) {
    this.totalPriceWithTax = totalPriceWithTax;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeliveryOrderEntryGroup deliveryOrderEntryGroup = (DeliveryOrderEntryGroup) o;
    return Objects.equals(this.deliveryAddress, deliveryOrderEntryGroup.deliveryAddress) &&
        Objects.equals(this.entries, deliveryOrderEntryGroup.entries) &&
        Objects.equals(this.quantity, deliveryOrderEntryGroup.quantity) &&
        Objects.equals(this.totalPriceWithTax, deliveryOrderEntryGroup.totalPriceWithTax);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deliveryAddress, entries, quantity, totalPriceWithTax);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeliveryOrderEntryGroup {\n");
    
    sb.append("    deliveryAddress: ").append(toIndentedString(deliveryAddress)).append("\n");
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    totalPriceWithTax: ").append(toIndentedString(totalPriceWithTax)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

