/*
 * Commerce Webservices v2
 * These services manage all of the common commerce functionality, and also include customizations from installed AddOns.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rockwell.cif.connector.hybris.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Representation of a search results pagination
 */
@ApiModel(description = "Representation of a search results pagination")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-23T22:16:40.723Z")



public class DeprecatedPagination {
  @SerializedName("currentPage")
  private Integer currentPage = null;

  @SerializedName("pageSize")
  private Integer pageSize = null;

  @SerializedName("sort")
  private String sort = null;

  @SerializedName("totalPages")
  private Integer totalPages = null;

  @SerializedName("totalResults")
  private Long totalResults = null;

  public DeprecatedPagination currentPage(Integer currentPage) {
    this.currentPage = currentPage;
    return this;
  }

   /**
   * The current page number. The first page is number zero (0), the second page is number one (1), and so on
   * @return currentPage
  **/
  @ApiModelProperty(value = "The current page number. The first page is number zero (0), the second page is number one (1), and so on")
  public Integer getCurrentPage() {
    return currentPage;
  }

  public void setCurrentPage(Integer currentPage) {
    this.currentPage = currentPage;
  }

  public DeprecatedPagination pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * The number of results per page. A page may have less results if there are less than a full page of results, only on the last page in the results
   * @return pageSize
  **/
  @ApiModelProperty(value = "The number of results per page. A page may have less results if there are less than a full page of results, only on the last page in the results")
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  public DeprecatedPagination sort(String sort) {
    this.sort = sort;
    return this;
  }

   /**
   * The selected sort code
   * @return sort
  **/
  @ApiModelProperty(value = "The selected sort code")
  public String getSort() {
    return sort;
  }

  public void setSort(String sort) {
    this.sort = sort;
  }

  public DeprecatedPagination totalPages(Integer totalPages) {
    this.totalPages = totalPages;
    return this;
  }

   /**
   * The total number of pages. This is the number of pages, each of pageSize, required to display the totalResults.
   * @return totalPages
  **/
  @ApiModelProperty(value = "The total number of pages. This is the number of pages, each of pageSize, required to display the totalResults.")
  public Integer getTotalPages() {
    return totalPages;
  }

  public void setTotalPages(Integer totalPages) {
    this.totalPages = totalPages;
  }

  public DeprecatedPagination totalResults(Long totalResults) {
    this.totalResults = totalResults;
    return this;
  }

   /**
   * The total number of matched results across all pages
   * @return totalResults
  **/
  @ApiModelProperty(value = "The total number of matched results across all pages")
  public Long getTotalResults() {
    return totalResults;
  }

  public void setTotalResults(Long totalResults) {
    this.totalResults = totalResults;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeprecatedPagination deprecatedPagination = (DeprecatedPagination) o;
    return Objects.equals(this.currentPage, deprecatedPagination.currentPage) &&
        Objects.equals(this.pageSize, deprecatedPagination.pageSize) &&
        Objects.equals(this.sort, deprecatedPagination.sort) &&
        Objects.equals(this.totalPages, deprecatedPagination.totalPages) &&
        Objects.equals(this.totalResults, deprecatedPagination.totalResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentPage, pageSize, sort, totalPages, totalResults);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeprecatedPagination {\n");
    
    sb.append("    currentPage: ").append(toIndentedString(currentPage)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
    sb.append("    totalResults: ").append(toIndentedString(totalResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

