/*
 * Commerce Webservices v2
 * These services manage all of the common commerce functionality, and also include customizations from installed AddOns.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rockwell.cif.connector.hybris.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ListAdaptedComponents
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-23T22:16:40.723Z")



public class ListAdaptedComponents {
  @SerializedName("component")
  private List<ComponentAdaptedData> component = null;

  @SerializedName("pagination")
  private Pagination pagination = null;

  @SerializedName("sorts")
  private List<Sort> sorts = null;

  public ListAdaptedComponents component(List<ComponentAdaptedData> component) {
    this.component = component;
    return this;
  }

  public ListAdaptedComponents addComponentItem(ComponentAdaptedData componentItem) {
    if (this.component == null) {
      this.component = new ArrayList<ComponentAdaptedData>();
    }
    this.component.add(componentItem);
    return this;
  }

   /**
   * Get component
   * @return component
  **/
  @ApiModelProperty(value = "")
  public List<ComponentAdaptedData> getComponent() {
    return component;
  }

  public void setComponent(List<ComponentAdaptedData> component) {
    this.component = component;
  }

  public ListAdaptedComponents pagination(Pagination pagination) {
    this.pagination = pagination;
    return this;
  }

   /**
   * Get pagination
   * @return pagination
  **/
  @ApiModelProperty(value = "")
  public Pagination getPagination() {
    return pagination;
  }

  public void setPagination(Pagination pagination) {
    this.pagination = pagination;
  }

  public ListAdaptedComponents sorts(List<Sort> sorts) {
    this.sorts = sorts;
    return this;
  }

  public ListAdaptedComponents addSortsItem(Sort sortsItem) {
    if (this.sorts == null) {
      this.sorts = new ArrayList<Sort>();
    }
    this.sorts.add(sortsItem);
    return this;
  }

   /**
   * Get sorts
   * @return sorts
  **/
  @ApiModelProperty(value = "")
  public List<Sort> getSorts() {
    return sorts;
  }

  public void setSorts(List<Sort> sorts) {
    this.sorts = sorts;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListAdaptedComponents listAdaptedComponents = (ListAdaptedComponents) o;
    return Objects.equals(this.component, listAdaptedComponents.component) &&
        Objects.equals(this.pagination, listAdaptedComponents.pagination) &&
        Objects.equals(this.sorts, listAdaptedComponents.sorts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(component, pagination, sorts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListAdaptedComponents {\n");
    
    sb.append("    component: ").append(toIndentedString(component)).append("\n");
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("    sorts: ").append(toIndentedString(sorts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

