/*
 * Commerce Webservices v2
 * These services manage all of the common commerce functionality, and also include customizations from installed AddOns.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rockwell.cif.connector.hybris.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Representation of an Order Status Update Element List
 */
@ApiModel(description = "Representation of an Order Status Update Element List")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-23T22:16:40.723Z")



public class OrderStatusUpdateElementList {
  @SerializedName("orderStatusUpdateElements")
  private List<OrderStatusUpdateElement> orderStatusUpdateElements = null;

  public OrderStatusUpdateElementList orderStatusUpdateElements(List<OrderStatusUpdateElement> orderStatusUpdateElements) {
    this.orderStatusUpdateElements = orderStatusUpdateElements;
    return this;
  }

  public OrderStatusUpdateElementList addOrderStatusUpdateElementsItem(OrderStatusUpdateElement orderStatusUpdateElementsItem) {
    if (this.orderStatusUpdateElements == null) {
      this.orderStatusUpdateElements = new ArrayList<OrderStatusUpdateElement>();
    }
    this.orderStatusUpdateElements.add(orderStatusUpdateElementsItem);
    return this;
  }

   /**
   * List of order status update elements
   * @return orderStatusUpdateElements
  **/
  @ApiModelProperty(value = "List of order status update elements")
  public List<OrderStatusUpdateElement> getOrderStatusUpdateElements() {
    return orderStatusUpdateElements;
  }

  public void setOrderStatusUpdateElements(List<OrderStatusUpdateElement> orderStatusUpdateElements) {
    this.orderStatusUpdateElements = orderStatusUpdateElements;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderStatusUpdateElementList orderStatusUpdateElementList = (OrderStatusUpdateElementList) o;
    return Objects.equals(this.orderStatusUpdateElements, orderStatusUpdateElementList.orderStatusUpdateElements);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderStatusUpdateElements);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderStatusUpdateElementList {\n");
    
    sb.append("    orderStatusUpdateElements: ").append(toIndentedString(orderStatusUpdateElements)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

