/*
 * Commerce Webservices v2
 * These services manage all of the common commerce functionality, and also include customizations from installed AddOns.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rockwell.cif.connector.hybris.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Representation of an Order Status Update Element
 */
@ApiModel(description = "Representation of an Order Status Update Element")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-23T22:16:40.723Z")



public class OrderStatusUpdateElement {
  @SerializedName("baseSiteId")
  private String baseSiteId = null;

  @SerializedName("code")
  private String code = null;

  @SerializedName("status")
  private String status = null;

  public OrderStatusUpdateElement baseSiteId(String baseSiteId) {
    this.baseSiteId = baseSiteId;
    return this;
  }

   /**
   * BaseSite identifier
   * @return baseSiteId
  **/
  @ApiModelProperty(value = "BaseSite identifier")
  public String getBaseSiteId() {
    return baseSiteId;
  }

  public void setBaseSiteId(String baseSiteId) {
    this.baseSiteId = baseSiteId;
  }

  public OrderStatusUpdateElement code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Code of update element of order status
   * @return code
  **/
  @ApiModelProperty(value = "Code of update element of order status")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public OrderStatusUpdateElement status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Status of update element
   * @return status
  **/
  @ApiModelProperty(value = "Status of update element")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderStatusUpdateElement orderStatusUpdateElement = (OrderStatusUpdateElement) o;
    return Objects.equals(this.baseSiteId, orderStatusUpdateElement.baseSiteId) &&
        Objects.equals(this.code, orderStatusUpdateElement.code) &&
        Objects.equals(this.status, orderStatusUpdateElement.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(baseSiteId, code, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderStatusUpdateElement {\n");
    
    sb.append("    baseSiteId: ").append(toIndentedString(baseSiteId)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

