/*
 * Commerce Webservices v2
 * These services manage all of the common commerce functionality, and also include customizations from installed AddOns.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rockwell.cif.connector.hybris.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Representation of a Promotion
 */
@ApiModel(description = "Representation of a Promotion")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-23T22:16:40.723Z")



public class Promotion {
  @SerializedName("code")
  private String code = null;

  @SerializedName("couldFireMessages")
  private List<String> couldFireMessages = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("enabled")
  private Boolean enabled = null;

  @SerializedName("endDate")
  private OffsetDateTime endDate = null;

  @SerializedName("firedMessages")
  private List<String> firedMessages = null;

  @SerializedName("priority")
  private Integer priority = null;

  @SerializedName("productBanner")
  private Image productBanner = null;

  @SerializedName("promotionGroup")
  private String promotionGroup = null;

  @SerializedName("promotionType")
  private String promotionType = null;

  @SerializedName("restrictions")
  private List<PromotionRestriction> restrictions = null;

  @SerializedName("startDate")
  private OffsetDateTime startDate = null;

  @SerializedName("title")
  private String title = null;

  public Promotion code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Code of the promotion
   * @return code
  **/
  @ApiModelProperty(value = "Code of the promotion")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public Promotion couldFireMessages(List<String> couldFireMessages) {
    this.couldFireMessages = couldFireMessages;
    return this;
  }

  public Promotion addCouldFireMessagesItem(String couldFireMessagesItem) {
    if (this.couldFireMessages == null) {
      this.couldFireMessages = new ArrayList<String>();
    }
    this.couldFireMessages.add(couldFireMessagesItem);
    return this;
  }

   /**
   * Message about promotion which is displayed when planning potential promotion. This field has higher priority over promotion description
   * @return couldFireMessages
  **/
  @ApiModelProperty(value = "Message about promotion which is displayed when planning potential promotion. This field has higher priority over promotion description")
  public List<String> getCouldFireMessages() {
    return couldFireMessages;
  }

  public void setCouldFireMessages(List<String> couldFireMessages) {
    this.couldFireMessages = couldFireMessages;
  }

  public Promotion description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of the promotion
   * @return description
  **/
  @ApiModelProperty(value = "Description of the promotion")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Promotion enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Boolean flag if promotion is enabled
   * @return enabled
  **/
  @ApiModelProperty(value = "Boolean flag if promotion is enabled")
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public Promotion endDate(OffsetDateTime endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Last date of validity of the promotion
   * @return endDate
  **/
  @ApiModelProperty(value = "Last date of validity of the promotion")
  public OffsetDateTime getEndDate() {
    return endDate;
  }

  public void setEndDate(OffsetDateTime endDate) {
    this.endDate = endDate;
  }

  public Promotion firedMessages(List<String> firedMessages) {
    this.firedMessages = firedMessages;
    return this;
  }

  public Promotion addFiredMessagesItem(String firedMessagesItem) {
    if (this.firedMessages == null) {
      this.firedMessages = new ArrayList<String>();
    }
    this.firedMessages.add(firedMessagesItem);
    return this;
  }

   /**
   * Message fired while the promotion is active. This is info how much you will get when applying the promotion
   * @return firedMessages
  **/
  @ApiModelProperty(value = "Message fired while the promotion is active. This is info how much you will get when applying the promotion")
  public List<String> getFiredMessages() {
    return firedMessages;
  }

  public void setFiredMessages(List<String> firedMessages) {
    this.firedMessages = firedMessages;
  }

  public Promotion priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Priority index as numeric value of the promotion. Higher number means higher priority
   * @return priority
  **/
  @ApiModelProperty(value = "Priority index as numeric value of the promotion. Higher number means higher priority")
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  public Promotion productBanner(Image productBanner) {
    this.productBanner = productBanner;
    return this;
  }

   /**
   * Image banner of the promotion
   * @return productBanner
  **/
  @ApiModelProperty(value = "Image banner of the promotion")
  public Image getProductBanner() {
    return productBanner;
  }

  public void setProductBanner(Image productBanner) {
    this.productBanner = productBanner;
  }

  public Promotion promotionGroup(String promotionGroup) {
    this.promotionGroup = promotionGroup;
    return this;
  }

   /**
   * Group of the promotion
   * @return promotionGroup
  **/
  @ApiModelProperty(value = "Group of the promotion")
  public String getPromotionGroup() {
    return promotionGroup;
  }

  public void setPromotionGroup(String promotionGroup) {
    this.promotionGroup = promotionGroup;
  }

  public Promotion promotionType(String promotionType) {
    this.promotionType = promotionType;
    return this;
  }

   /**
   * Type of the promotion
   * @return promotionType
  **/
  @ApiModelProperty(value = "Type of the promotion")
  public String getPromotionType() {
    return promotionType;
  }

  public void setPromotionType(String promotionType) {
    this.promotionType = promotionType;
  }

  public Promotion restrictions(List<PromotionRestriction> restrictions) {
    this.restrictions = restrictions;
    return this;
  }

  public Promotion addRestrictionsItem(PromotionRestriction restrictionsItem) {
    if (this.restrictions == null) {
      this.restrictions = new ArrayList<PromotionRestriction>();
    }
    this.restrictions.add(restrictionsItem);
    return this;
  }

   /**
   * List of promotion restrictions
   * @return restrictions
  **/
  @ApiModelProperty(value = "List of promotion restrictions")
  public List<PromotionRestriction> getRestrictions() {
    return restrictions;
  }

  public void setRestrictions(List<PromotionRestriction> restrictions) {
    this.restrictions = restrictions;
  }

  public Promotion startDate(OffsetDateTime startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * The initial date of the promotion
   * @return startDate
  **/
  @ApiModelProperty(value = "The initial date of the promotion")
  public OffsetDateTime getStartDate() {
    return startDate;
  }

  public void setStartDate(OffsetDateTime startDate) {
    this.startDate = startDate;
  }

  public Promotion title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Promotion title
   * @return title
  **/
  @ApiModelProperty(value = "Promotion title")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Promotion promotion = (Promotion) o;
    return Objects.equals(this.code, promotion.code) &&
        Objects.equals(this.couldFireMessages, promotion.couldFireMessages) &&
        Objects.equals(this.description, promotion.description) &&
        Objects.equals(this.enabled, promotion.enabled) &&
        Objects.equals(this.endDate, promotion.endDate) &&
        Objects.equals(this.firedMessages, promotion.firedMessages) &&
        Objects.equals(this.priority, promotion.priority) &&
        Objects.equals(this.productBanner, promotion.productBanner) &&
        Objects.equals(this.promotionGroup, promotion.promotionGroup) &&
        Objects.equals(this.promotionType, promotion.promotionType) &&
        Objects.equals(this.restrictions, promotion.restrictions) &&
        Objects.equals(this.startDate, promotion.startDate) &&
        Objects.equals(this.title, promotion.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, couldFireMessages, description, enabled, endDate, firedMessages, priority, productBanner, promotionGroup, promotionType, restrictions, startDate, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Promotion {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    couldFireMessages: ").append(toIndentedString(couldFireMessages)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    firedMessages: ").append(toIndentedString(firedMessages)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    productBanner: ").append(toIndentedString(productBanner)).append("\n");
    sb.append("    promotionGroup: ").append(toIndentedString(promotionGroup)).append("\n");
    sb.append("    promotionType: ").append(toIndentedString(promotionType)).append("\n");
    sb.append("    restrictions: ").append(toIndentedString(restrictions)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

