/*
 * Commerce Webservices v2
 * These services manage all of the common commerce functionality, and also include customizations from installed AddOns.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rockwell.cif.connector.hybris.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Response body fields which will be returned while fetching the list of country&#39;s regions.
 */
@ApiModel(description = "Response body fields which will be returned while fetching the list of country's regions.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-23T22:16:40.723Z")



public class Region {
  @SerializedName("countryIso")
  private String countryIso = null;

  @SerializedName("isocode")
  private String isocode = null;

  @SerializedName("isocodeShort")
  private String isocodeShort = null;

  @SerializedName("name")
  private String name = null;

  public Region countryIso(String countryIso) {
    this.countryIso = countryIso;
    return this;
  }

   /**
   * Country code in iso format
   * @return countryIso
  **/
  @ApiModelProperty(value = "Country code in iso format")
  public String getCountryIso() {
    return countryIso;
  }

  public void setCountryIso(String countryIso) {
    this.countryIso = countryIso;
  }

  public Region isocode(String isocode) {
    this.isocode = isocode;
    return this;
  }

   /**
   * Country and Region code in iso format
   * @return isocode
  **/
  @ApiModelProperty(value = "Country and Region code in iso format")
  public String getIsocode() {
    return isocode;
  }

  public void setIsocode(String isocode) {
    this.isocode = isocode;
  }

  public Region isocodeShort(String isocodeShort) {
    this.isocodeShort = isocodeShort;
    return this;
  }

   /**
   * Region code in short iso form
   * @return isocodeShort
  **/
  @ApiModelProperty(value = "Region code in short iso form")
  public String getIsocodeShort() {
    return isocodeShort;
  }

  public void setIsocodeShort(String isocodeShort) {
    this.isocodeShort = isocodeShort;
  }

  public Region name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the region
   * @return name
  **/
  @ApiModelProperty(value = "Name of the region")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Region region = (Region) o;
    return Objects.equals(this.countryIso, region.countryIso) &&
        Objects.equals(this.isocode, region.isocode) &&
        Objects.equals(this.isocodeShort, region.isocodeShort) &&
        Objects.equals(this.name, region.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countryIso, isocode, isocodeShort, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Region {\n");
    
    sb.append("    countryIso: ").append(toIndentedString(countryIso)).append("\n");
    sb.append("    isocode: ").append(toIndentedString(isocode)).append("\n");
    sb.append("    isocodeShort: ").append(toIndentedString(isocodeShort)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

