/*
 * Commerce Webservices v2
 * These services manage all of the common commerce functionality, and also include customizations from installed AddOns.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rockwell.cif.connector.hybris.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Representation of a Reset Password
 */
@ApiModel(description = "Representation of a Reset Password")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-23T22:16:40.723Z")



public class ResetPassword {
  @SerializedName("newPassword")
  private String newPassword = null;

  @SerializedName("token")
  private String token = null;

  public ResetPassword newPassword(String newPassword) {
    this.newPassword = newPassword;
    return this;
  }

   /**
   * new password string which is required to complete process of resetting password
   * @return newPassword
  **/
  @ApiModelProperty(required = true, value = "new password string which is required to complete process of resetting password")
  public String getNewPassword() {
    return newPassword;
  }

  public void setNewPassword(String newPassword) {
    this.newPassword = newPassword;
  }

  public ResetPassword token(String token) {
    this.token = token;
    return this;
  }

   /**
   * token value which will be generated as unique string that will be sent with email to allow user for completing reset-password operation
   * @return token
  **/
  @ApiModelProperty(required = true, value = "token value which will be generated as unique string that will be sent with email to allow user for completing reset-password operation")
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResetPassword resetPassword = (ResetPassword) o;
    return Objects.equals(this.newPassword, resetPassword.newPassword) &&
        Objects.equals(this.token, resetPassword.token);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newPassword, token);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResetPassword {\n");
    
    sb.append("    newPassword: ").append(toIndentedString(newPassword)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

