/*
 * Commerce Webservices v2
 * These services manage all of the common commerce functionality, and also include customizations from installed AddOns.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rockwell.cif.connector.hybris.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Representation of a Spell Checker Suggestion
 */
@ApiModel(description = "Representation of a Spell Checker Suggestion")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-23T22:16:40.723Z")



public class SpellingSuggestion {
  @SerializedName("query")
  private String query = null;

  @SerializedName("suggestion")
  private String suggestion = null;

  public SpellingSuggestion query(String query) {
    this.query = query;
    return this;
  }

   /**
   * Query for spelling suggestion
   * @return query
  **/
  @ApiModelProperty(value = "Query for spelling suggestion")
  public String getQuery() {
    return query;
  }

  public void setQuery(String query) {
    this.query = query;
  }

  public SpellingSuggestion suggestion(String suggestion) {
    this.suggestion = suggestion;
    return this;
  }

   /**
   * Spelling suggestion
   * @return suggestion
  **/
  @ApiModelProperty(value = "Spelling suggestion")
  public String getSuggestion() {
    return suggestion;
  }

  public void setSuggestion(String suggestion) {
    this.suggestion = suggestion;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpellingSuggestion spellingSuggestion = (SpellingSuggestion) o;
    return Objects.equals(this.query, spellingSuggestion.query) &&
        Objects.equals(this.suggestion, spellingSuggestion.suggestion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(query, suggestion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpellingSuggestion {\n");
    
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    suggestion: ").append(toIndentedString(suggestion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

